/*
 * Stoatworks Labs - About window data for Teletext.
 *
 * PROVISIONAL hand copy, adapted from a sibling (2026-09-24). The fleet's
 * copies are GENERATED by stoatworks-backend/scripts/sync-about.py from the
 * website's projects.json; this repo is not registered there yet, so this
 * file will be overwritten by the first sync. `guide` is empty because no
 * user guide exists yet: an empty link is left out of the button list rather
 * than shown as a button that opens a 404.
 *
 * `version` here is a fallback read from this repo's own manifest at sync
 * time. Anything with a build step injects the real one at build time and
 * overrides this.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "Teletext";
    inline constexpr auto slug = "teletext";
    inline constexpr auto hook = "A picture as Level 1 teletext mosaics, for Resolume";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "";
    inline constexpr auto page = "https://stoatworks-labs.com/software/teletext/";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/teletext";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
